### ISSUE TITLE
DTS equipment

### ISSUE THREAD

**Issue by Paulo-Mazzo** [foobarbecue/fodts_plotter#1]
Hi @foobarbecue! 
It seams you did a great work here. Congrats!

I have a question though. With wich DTS equipments can you work with this project? I work with AP Sensing DTS, and I was wondering if this code would be able to communicate with my equipment.

Does the script "dts.py" plots live traces from DTS?

**Comment by foobarbecue** [comment]
Hi @Paulo-Mazzo , thanks, but wow, this is an OLD repo. I'm not sure if it's of any use anymore. Mostly, this was for Ch3 of my PhD dissertation: https://aaroncurt.is/paper/curtis2016-phd_diss.pdf . It never plotted live traces, just recorded traces from a Sensornet Oryx.

**Comment by Paulo-Mazzo** [comment]
Thanks
